ALTER TABLE public.cars
  ADD COLUMN IF NOT EXISTS power INTEGER,
  ADD COLUMN IF NOT EXISTS drive_type TEXT,
  ADD COLUMN IF NOT EXISTS body_type TEXT,
  ADD COLUMN IF NOT EXISTS seats INTEGER,
  ADD COLUMN IF NOT EXISTS doors INTEGER,
  ADD COLUMN IF NOT EXISTS first_registration TEXT,
  ADD COLUMN IF NOT EXISTS interior_color TEXT,
  ADD COLUMN IF NOT EXISTS owners INTEGER,
  ADD COLUMN IF NOT EXISTS next_eu TEXT,
  ADD COLUMN IF NOT EXISTS range_km INTEGER;
